version: '3.4'

services:
  userservice:
    image: userservice
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 3010:3010
      - 9229:9229
    command: ["node", "--inspect=0.0.0.0:9229", "server.js"]
