version: '3.4'

services:
  postservice:
    image: postservice
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3011:3011
    depends_on:
      - mongo
      - minio

  mongo:
    image: mongo:latest
    ports:
      - "27021:27017"
    volumes:
      - post-data:/data/db
  minio:
    image: minio/minio:latest
    environment:
      - MINIO_ACCESS_KEY='B0P7FMRJgKcCXfxg7jSQ'
      - MINIO_SECRET_KEY='8r43tyqICTmKfppfIa9N1YiuvwXEH2SqNpXzKIed'
    command: server --address 0.0.0.0:9000 /data
volumes:
  post-data:
