version: '3.4'

services:
  postservice:
    image: postservice
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 3011:3011
      - 9229:9229
    command: ["node", "--inspect=0.0.0.0:9229", "server.js"]
